name: Test backend terraform files

on:
  push:
    paths:
      - 'terraform-backend/**'
  workflow_dispatch:

jobs:
  terraform-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
  
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.12.2

    - name: Terraform initialize
      working-directory: terraform-backend
      run: terraform init

    - name: Terraform validate
      working-directory: terraform-backend
      run: terraform validate

    - name: Terraform plan
      working-directory: terraform-backend
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
      run: terraform plan
